sudo: required
dist: trusty
language: cpp
compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION: 1.8.0
install:
  - docker pull hnagamin/llvm-3.9:latest
script:
  - mkdir build
  - docker-compose run workspace bash -c "cd /worktree/build && cmake .."
  - docker-compose run workspace bash -c "cd /worktree/build && VERBOSE=1 make"
