sudo: required
dist: trusty
language: cpp
compiler:
  - clang-3.6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
script:
  - export CXX="clang++-3.6";
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - VERBOSE=1 make
